Ios picker
csci0466-s22/project-codedash pull request #25
Opened 2022-05-11 21:27 UTC by waynew99

This branch is based on androidCreate on Wednesday after noon. It contains code in androidCreate that was not yet merged into main.

2022-05-13 18:17 UTC, Nicholas-Sliter requested changes

2022-05-13 18:17 UTC, Nicholas-Sliter commented on components/Code2/Code2.tsx
> +function Code2({ code, language, inEditor = false }: CodeProps) {
We probably need a better name for code2

2022-05-13 18:17 UTC, Nicholas-Sliter commented on components/Code2/Code2.tsx
> +    //this function is now obsolete, refactor to simple style just in the stylesheet file
do this

2022-05-13 18:17 UTC, Nicholas-Sliter commented on components/Code2/Code2.tsx
> +                          //fontWeight: props.style?.fontWeight ?? "normal",
remove

2022-05-13 18:17 UTC, Nicholas-Sliter commented on components/Code2/Code2.tsx
> +                      {!token.empty ? props.children : "\n" /* Not sure we need this*/ }
we do

2022-05-13 18:17 UTC, Nicholas-Sliter commented on components/CodeEditor/CodeEditor.tsx
> +        //selection={{start: cursorPosition.start, end: cursorPosition.end}}
remove

2022-05-13 18:24 UTC, Cliffy2000 reviewed
great work!

2022-05-13 18:24 UTC, Cliffy2000 approved these changes
actually an approve

2022-05-14 02:41 UTC, Nicholas-Sliter approved these changes
LGTM!

2022-05-14 02:41 UTC, merged